[ADD] chocolatine.yml

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,13 +1,33 @@
 name: repository_size
 run-name: ${{ github.actor }} asking for main action
-on: push
+on: [push, pull_request]
 jobs:
 
-  repository_size:
+  check_coding_style:
     runs-on: ubuntu-latest
+    name: check_coding_style
+    container: ghcr.io/epitech/coding-style-checker:latest
     steps:
+
+      - name: Checkout GH repository
       - uses:  actions/checkout@v3
         with:
           repository: ''
-      - run: echo ${GITHUB_REF##*/}
-      - run: du -skh --exclude=".git"
+
+      - name: run conding-style.sh
+        run: check.sh . .
+
+      - name: Display banana report
+        run: cat coding-style-reports.log
+
+      - name: report banana result
+        run: |
+          NB_ERROR=$(cat coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+            ERRORS=$(cat coding-style-reports.log);
+              echo "Banana found $NB_ERROR error(s)"
+              echo "$ERRORS"
+              exit 1
+          fi
+          echo "Everything is good ! Keep on coding !"
+          exit 0
